import { ProductData } from "../types";

export const products: ProductData[] = [
  {
    id: "1",
    productName: "Premium Maize",
    storeName: "AgroFarm Ltd",
    currency: "NGN",
    amount: 12000,
    imgUrl: "/assets/dummy/Produt img.png",
    isInWishList: false,
    unit: "50kg",
    totalReviews: 34,
  },
  {
    id: "2",
    productName: "Raw Cashew Nuts",
    storeName: "NutriHarvest",
    currency: "USD",
    amount: 85,
    imgUrl: "/assets/dummy/Produt img1.png",
    isInWishList: true,
    unit: "25kg",
    totalReviews: 21,
  },
  {
    id: "3",
    productName: "Processed Rice",
    storeName: "Golden Grains",
    currency: "NGN",
    amount: 45000,
    imgUrl: "/assets/dummy/Produt img2.png",
    isInWishList: false,
    unit: "50kg",
    totalReviews: 58,
  },
  {
    id: "4",
    productName: "Soybeans",
    storeName: "FarmLink Africa",
    currency: "NGN",
    amount: 30000,
    imgUrl: "/assets/dummy/Produt img3.png",
    isInWishList: false,
    unit: "50kg",
    totalReviews: 19,
  },
  {
    id: "5",
    productName: "Sesame Seeds",
    storeName: "Seed Masters",
    currency: "USD",
    amount: 120,
    imgUrl: "/assets/dummy/Produt img4.png",
    isInWishList: true,
    unit: "30kg",
    totalReviews: 42,
  },
  {
    id: "6",
    productName: "Dried Ginger",
    storeName: "Spice World",
    currency: "NGN",
    amount: 25000,
    imgUrl: "/assets/dummy/Produt img5.png",
    isInWishList: false,
    unit: "20kg",
    totalReviews: 27,
  },
  {
    id: "7",
    productName: "Palm Oil",
    storeName: "Nature Oils",
    currency: "NGN",
    amount: 18000,
    imgUrl: "/assets/dummy/Produt img.png",
    isInWishList: true,
    unit: "25 liters",
    totalReviews: 63,
  },
  {
    id: "8",
    productName: "Cassava Flour",
    storeName: "Root Foods",
    currency: "NGN",
    amount: 9000,
    imgUrl: "/assets/dummy/Produt img.png",
    isInWishList: false,
    unit: "10kg",
    totalReviews: 15,
  },
  {
    id: "9",
    productName: "Groundnuts",
    storeName: "FarmFresh Hub",
    currency: "USD",
    amount: 60,
    imgUrl: "/assets/dummy/Produt img5.png",
    isInWishList: true,
    unit: "25kg",
    totalReviews: 29,
  },
  {
    id: "10",
    productName: "Corn Flour",
    storeName: "Millers Co.",
    currency: "NGN",
    amount: 11000,
    imgUrl: "/assets/dummy/Produt img3.png",
    isInWishList: false,
    unit: "15kg",
    totalReviews: 11,
  },
];
