import { ProductData } from "../types";

export const products: ProductData[] = [
  {
    id: "1",
    slug: "premium-maize",
    productName: "Premium Maize",
    storeName: "AgroFarm Ltd",
    currency: "NGN",
    amount: 12000,
    imgUrl: "/assets/dummy/Produt img.png",
    isInWishList: false,
    unit: "50kg",
    totalReviews: 34,
  },
  {
    id: "2",
    slug: "raw-cashew-nuts",
    productName: "Raw Cashew Nuts",
    storeName: "NutriHarvest",
    currency: "USD",
    amount: 85,
    imgUrl: "/assets/dummy/Produt img1.png",
    isInWishList: true,
    unit: "25kg",
    totalReviews: 21,
  },
  {
    id: "3",
    slug: "processed-rice",
    productName: "Processed Rice",
    storeName: "Golden Grains",
    currency: "NGN",
    amount: 45000,
    imgUrl: "/assets/dummy/Produt img2.png",
    isInWishList: false,
    unit: "50kg",
    totalReviews: 58,
  },
  {
    id: "4",
    slug: "soybeans",
    productName: "Soybeans",
    storeName: "FarmLink Africa",
    currency: "NGN",
    amount: 30000,
    imgUrl: "/assets/dummy/Produt img3.png",
    isInWishList: false,
    unit: "50kg",
    totalReviews: 19,
  },
  {
    id: "5",
    slug: "sesame-seeds",
    productName: "Sesame Seeds",
    storeName: "Seed Masters",
    currency: "USD",
    amount: 120,
    imgUrl: "/assets/dummy/Produt img4.png",
    isInWishList: true,
    unit: "30kg",
    totalReviews: 42,
  },
  {
    id: "6",
    slug: "dried-ginger",
    productName: "Dried Ginger",
    storeName: "Spice World",
    currency: "NGN",
    amount: 25000,
    imgUrl: "/assets/dummy/Produt img5.png",
    isInWishList: false,
    unit: "20kg",
    totalReviews: 27,
  },
  {
    id: "7",
    slug: "palm-oil",
    productName: "Palm Oil",
    storeName: "Nature Oils",
    currency: "NGN",
    amount: 18000,
    imgUrl: "/assets/dummy/Produt img.png",
    isInWishList: true,
    unit: "25 liters",
    totalReviews: 63,
  },
  {
    id: "8",
    slug: "cassava-flour",
    productName: "Cassava Flour",
    storeName: "Root Foods",
    currency: "NGN",
    amount: 9000,
    imgUrl: "/assets/dummy/Produt img.png",
    isInWishList: false,
    unit: "10kg",
    totalReviews: 15,
  },
  {
    id: "9",
    slug: "groundnuts",
    productName: "Groundnuts",
    storeName: "FarmFresh Hub",
    currency: "USD",
    amount: 60,
    imgUrl: "/assets/dummy/Produt img5.png",
    isInWishList: true,
    unit: "25kg",
    totalReviews: 29,
  },
  {
    id: "10",
    slug: "corn-flour",
    productName: "Corn Flour",
    storeName: "Millers Co.",
    currency: "NGN",
    amount: 11000,
    imgUrl: "/assets/dummy/Produt img3.png",
    isInWishList: false,
    unit: "15kg",
    totalReviews: 11,
  },
  {
    id: "11",
    slug: "dangote-cement",
    productName: "Dangote Cement",
    storeName: "Dangote Industries",
    currency: "NGN",
    amount: 9025,
    imgUrl: "/assets/dummy/Frame 31.png",
    isInWishList: false,
    unit: "bag",
    totalReviews: 128,
  },
  {
    id: "12",
    slug: "premium-polo-shirt",
    productName: "Premium Polo Shirt",
    storeName: "Naija Threads",
    currency: "USD",
    amount: 12,
    imgUrl: "/assets/dummy/Frame 32.png",
    isInWishList: false,
    unit: "piece",
    totalReviews: 46,
  },
  {
    id: "13",
    slug: "dangote-block-cement",
    productName: "Block Moulding Cement",
    storeName: "Dangote Industries",
    currency: "NGN",
    amount: 9150,
    imgUrl: "/assets/dummy/Frame 33.png",
    unit: "bag",
    totalReviews: 74,
  },
  {
    id: "14",
    slug: "dangote-high-strength-cement",
    productName: "High Strength Cement",
    storeName: "Dangote Industries",
    currency: "NGN",
    amount: 10200,
    imgUrl: "/assets/dummy/Frame 34.png",
    unit: "bag",
    totalReviews: 91,
  },
  {
    id: "15",
    slug: "dangote-concrete-mix",
    productName: "Ready Concrete Mix",
    storeName: "Dangote Industries",
    currency: "NGN",
    amount: 11800,
    imgUrl: "/assets/dummy/Frame 35.png",
    unit: "bag",
    totalReviews: 52,
  },
  {
    id: "16",
    slug: "classic-cotton-tee",
    productName: "Classic Cotton Tee",
    storeName: "Naija Threads",
    currency: "USD",
    amount: 9,
    imgUrl: "/assets/dummy/Produt img.png",
    unit: "piece",
    totalReviews: 32,
  },
  {
    id: "17",
    slug: "corporate-polo-shirt",
    productName: "Corporate Polo Shirt",
    storeName: "Naija Threads",
    currency: "USD",
    amount: 14,
    imgUrl: "/assets/dummy/Produt img1.png",
    unit: "piece",
    totalReviews: 39,
  },
  {
    id: "18",
    slug: "premium-workwear-shirt",
    productName: "Premium Workwear Shirt",
    storeName: "Naija Threads",
    currency: "USD",
    amount: 16,
    imgUrl: "/assets/dummy/Produt img2.png",
    unit: "piece",
    totalReviews: 28,
  },
];
